# Generated by Django 3.1 on 2020-08-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3000)),
                ('photo', models.FileField(blank=True, null=True, upload_to='cc')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(default='', max_length=3000)),
                ('name_eng', models.CharField(default='', max_length=3000)),
                ('photo', models.FileField(blank=True, null=True, upload_to='c')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardcategory', to='flashcards.cardcategory')),
            ],
        ),
    ]
