# Generated by Django 3.1 on 2020-08-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['name_tr']},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=3000, unique=True)),
                ('cards', models.ManyToManyField(to='flashcards.Card')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
